### ISSUE TITLE
Découvrir d'autres plans

### ISSUE THREAD

**Issue by metallicanard** [restimel/insideWeCube#3]
Salut ! Je me permets de t'écrire ce message pour savoir si tu pouvais corriger ton appli Insidewecube, dans la section découvrir d'autres plans, sur PC il est impossible de sélectionner les plans qu'on a, et sur téléphone, on peut mais on ne peut pas valider...
Merci d'avance

**Comment by restimel** [comment]
Bonjour,
Je vais aller regarder ce que je peux faire, la section "Découvrir d'autre
plans" était une des dernière sections ajoutées et contient de trop
nombreux problèmes. Vu que le code est assez vieux je ne sais pas ce que je
pourrai vraiment faire (mais cela risque de me prendre du temp).
J'essaierai de te tenir au courant,

Cordialement,
Restimel

**Comment by metallicanard** [comment]
Très bien, c'était juste une suggestion, ne te sens surtout pas obligé de
le faire, je me doute bien que tu as plus important en ce moment !
Passe de bonnes fêtes
Hugo

**Comment by restimel** [comment]
Bonjour,
Je viens de pousser une correction pour la simple selection. Toutefois il
reste un petit problème de saut quand on selectionne un niveau qui est plus
bas, le navigateur revient vers le début de la selection (ce problème n'a
pas lieu quand on maintient ctrl appuyé). Il faudrait réécrire le composant
en entier, du coup je ne pense pas corriger ce pbl (car en létat il reste
utilsable même si c'est ennuyeux).

Je regarderais demain pour le problème sur téléphone (sauf s'il a aussi été
corrigé en même temps).

Merci pour ton retour et passe de bonnes fêtes également,
Restimel

**Comment by metallicanard** [comment]
Wow ! Merci ! Je suis impressionné  du nombre de possibilités
Merci !!

**Comment by metallicanard** [comment]
La fonction mobile marche niquel ! Merci à toi ! :)

**Comment by restimel** [comment]
Super!
Je n'avais pas réussi à reproduire le problème (il devait donc être lié au problème fixé).

Je suis content que le projet te plaise :)
