### ISSUE TITLE
Discordance de niveau de difficulté entre page "Découvrir d'autres plans" et "Gérer son cube"

### ISSUE THREAD

**Issue by RickDangerous38** [restimel/insideWeCube#4]
Bonjour,

Tout d'abord bravo pour ton site, tu as du bien t'éclater à modéliser tous les plateux de presque tous les modèles de cubes et à créer des algos de folie pour les différentes fonctionnalités de gestion/analyse de parcours, etc.. Chapeau !

Je me permets de te logguer ce bug car je voulais profiter de ton site pour me fabriquer d'autres combinaisons de cubes à partir des modèles de la série 0 que je possède depuis quelques semaines seulement, pour en faire des customs assez difficile.

Après avoir choisi par exemple les 7 plateaux du modèle Awful0 dans la section "Découvrir d'autres plans", et lancé la moulinette, je trouve 3 résultats de couleur de difficulté "rouge". 

Maisq quand je bascule dans la section "Gérer son cube" et que je charge les plateaux dans l'ordre indiqué par l'une ou l'autre des combinaisons "rouge" que j'ai repérées, le résultat donne une difficulté "verte" donc assez facile.

==> Du coup quelle est la difficulté réelle de la combinaison en question ? 

Si tu as le temps de jeter un oeil , merci d'avance car je souhaite imprimer des petits plans des faces du cube custom que je veux me fabriquer mais pour le moment je ne sais pas lesquels imprimer ;-)

**Comment by restimel** [comment]
Bonjour,

Merci pour tes retours, ça fait toujours plaisir de voir que ce projet est toujours apprécié.

Je viens effectivement de tester la combinaison Awful0-1, Awful0-5, Awful0-3, Awful0-6, Awful0-4, Awful0-2, Awful0-7 qui est mis en rouge, dans "Découvrir d'autre plans" et qui est ensuite estimer en vert dans l'analyse "gérér son cube".

J'aurai plutot tendance à faire confiance à la partie "gérer son cube" qui est plus stable (et donne plus de détail sur le calcul).
Le cube en question n'ayant pas de mouvement difficile (des mouvements en diagonal) ne me semble effectivement pas trop dur.
Le problème apparait aussi pourle cube de base qui mis en orange dans la recherche de plans et en rouge dans la gestion de cube.

Les couleurs semblent donc etre mal estimé dans la recherche de plans :'(
Je vais essayer de regarder ce problème aussi vite que possible

**Comment by restimel** [comment]
Bonjour,

Je viens de pousser la version 1.3.2 qui fixe ce problème.
Il est possible que la génération des cubes soit légèrement plus lente (ce qui ne devrait pas trop se ressentir sur 1 seul cube).

**Comment by RickDangerous38** [comment]
Merci pour ta réactivité, en effet après quelques tests de combinaisons, je vois déjà plus de cohérence entre les couleurs de difficulté entre les cubes sortis du moteur de recherche et leur reproduction dans la page "Gérer son cube" (pas tout le temps identiques mais on s'en rapproche)

J'irai jeter un oeil par curiosité pour voir ces algos de fou qui peuvent mettre le ventilo du PC en PLS si on choisit trop de plateaux avant de lancer la recherche (Temps estimé de 13 ans si on choisit tous les cubes MDR !)

PS : Attention quand tu as mis à jour la page "A propos" la date de la nouvelle version, tu as mis l'année 2020 , on vient de passer à 2021 ;-)

**Comment by restimel** [comment]
> PS : Attention quand tu as mis à jour la page "A propos" la date de la nouvelle version, tu as mis l'année 2020 , on vient de passer à 2021 ;-)

Arg! Merci pour cette remarque. C'est maintenant corrigé
